name: Render and Update Index

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.340

      - name: Render and Update Index
        run: |
          # Render QMD files
          quarto render --from Quarto-files --to _site --html
          
          # Update index.html
          echo "<html><head><title>Index</title></head><body>" > _site/index.html
          for file in Quarto-files/*.qmd; do
            filename=$(basename "$file")
            filename_no_ext="${filename%.*}"
            echo "<a href='${filename_no_ext}.html'>${filename_no_ext}</a><br>" >> _site/index.html
          done
          echo "</body></html>" >> _site/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site
