name: Render and Update Index

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install rmarkdown package
        run: |
          Rscript -e 'install.packages("rmarkdown")'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.340

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages # renderred html files will be pushed here
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions

      - name: Update Index
        run: |
            # Update index.html
            echo "<html><head><title>Index</title></head><body>" > _site/index.html
            for file in Quarto-files/*.qmd; do
              filename=$(basename "$file")
              filename_no_ext="${filename%.*}"
              echo "<a href='${filename_no_ext}.html'>${filename_no_ext}</a><br>" >> _site/index.html
            done
            echo "</body></html>" >> _site/index.html